version: "3"
services:
  web:
    build: ./backend-liverpool
    ports:
      - 7000:5000
    environment:
      - FLASK_ENV=development
    depends_on:
      - liverpool-db

  liverpool-db:
    container_name: liverpool_database
    image: postgres:16.3
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nano3110
      - POSTGRES_DB=liverdb

  frontend-store:
    build: ./frontend-liverpool
    volumes:
      - ./frontend-liverpool/src:/usr/src/app/src
    command: sh -c "npm run build && npm run start"
    ports:
      - 7001:3000
